### ISSUE TITLE
Question regarding `NodeRef`s

### ISSUE THREAD

**Issue by mal-tee** [ShiftLeftSecurity/codepropertygraph#1553]
Hi!

As there is no discussion/Q&A section activated for this repo, I'll ask here.

I am trying to understand how to apply the knowledge of overflowdb's README regarding NodeRefs.
> That's why you should never hold a (strong) reference onto them in your main application: it would inhibit the overflow mechanism.

If I understand correctly, one should only hold onto NodeRefs, instead of the "full" nodes. How do I do this when using the cpg? 

Let's say I have this example code:

```scala
val nodes = cpg.call("name")
```

How do I get the NodeRefs belonging to these nodes? Should I cast them? (NodeRefs seems to take type parameters?)

 ---
 On a different note:
 
 `cpg.all` returns `StoredNodes`. Are they related to NodeRefs or sth. different altogether? I couldn't find documentation about them, or source code for that matter.

Thanks in advance!

**Comment by mpollmeier** [comment]
The public api is designed so you'll do the right thing by default. In other words, you'll get NodeRefs, because a `Call` *is a* NodeRef:
```
joern> val call = cpg.call.head
call: Call = Call(
  id -> 350254634311902973L,
  argumentIndex -> 7,
  argumentName -> None,
  code -> "pat == null",
  columnNumber -> None,
  dispatchType -> "STATIC_DISPATCH",
  dynamicTypeHintFullName -> ArraySeq(),
  lineNumber -> None,
  methodFullName -> "<operator>.equals",
  name -> "<operator>.equals",
  order -> 7,
  signature -> "",
  typeFullName -> "<empty>"
)

joern> call.isInstanceOf[NodeRef[_]]
res6: Boolean = true

joern> call.isInstanceOf[NodeDb]
res7: Boolean = false

```
You can pass them around and store them in your maps/lists/whereever, they are just a thin reference to the actual data. What you should *not* do is hold onto the `NodeDb` instance, which you can get via `call.get`. On low memory, overflowdb drops the on-heap instance to clear some space, and will use the id from the `NodeRef` instance to load it back from disk if required. 


The domain specific nodes and edges are generated based on the [schema](https://github.com/ShiftLeftSecurity/codepropertygraph/tree/master/schema/src/main/scala/io/shiftleft/codepropertygraph/schema). To see the sources, simply run `sbt compile` and have a look in `schema/target/scala-3.1.0/src_managed/main/overflowdb-codegen/io/shiftleft/codepropertygraph/generated`

**Comment by mal-tee** [comment]
That makes sense, thank you very much!
