### ISSUE TITLE
Build and deploy python library `cpgclientlib`

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/codepropertygraph#181]
Travis currently only builds and deploys the scala code in this repository. `cpgclientlib` needs to be built and deployed to PyPi. Alternatively, it might be a better choice to simply host that library in another repository.

**Comment by fabsx00** [comment]
Python tests can currently be run as follows:
```
cd cpgclientlib
./runtests.sh
```
The directory `cpgclientlib` contains a python wheel with a `setup.py`. `setup.py` determines the version of `codepropertygraph` from git automatically.

@mpollmeier do you think it's a good idea if we publish artifacts automatically to PyPi, or should we maybe offer them via github releases? Opinions?

**Comment by mpollmeier** [comment]
if `cpgclientlib` naturally belongs into this repo and is released together with codepropertygraph, it sounds like we should build and release it together. here's the docs for travis-ci and python (see `.travis.yml` in the repo): https://docs.travis-ci.com/user/languages/python/

That being said, I've never deployed anything to PyPi, so I don't know what's involved. 
Suggestion: have a look at that docs page and see if you can configure the .travis.yml to do what you want. If it's unclear, can you list the steps necessary in order to publish to PyPi? Do we need some credentials and gpg keys for that?

**Comment by mpollmeier** [comment]
also note https://docs.travis-ci.com/user/deployment/pypi/

**Comment by fabsx00** [comment]
Yes, `cpgclientlib` naturally belongs to `codepropertygraph` and the two should be released together. That's also why I believe using the same version number makes sense. I had actually reviewed the docs you had posted earlier, but I was wondering how we can Jenkins to build, test, and release both the Scala and the Python code. It seems like we can only specify one language. I did see that there is the possibility to specify a build matrix to possibly resolve this. Have you done something like this in the past? Also, do you have a local travis setup with which you test travis changes? I fear testing out travis builds directly on master and breaking everything for several hours.

**Comment by mpollmeier** [comment]
> do you have a local travis setup with which you test travis changes? I fear testing out travis builds directly on master and breaking everything for several hours.

Just add your branch to the whitelist of branches here: https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/.travis.yml#L6
It will only run the `test` stage, not `release`, because of this condition: https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/.travis.yml#L31-L32

There's a few ways on how to handle multiple languages, e.g.
* trigger the python release from sbt, i.e. https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/.travis.yml#L39 would include another sbt task like `releaseCpgClientLib`, which you add to the build and e.g. call a shell file or so
* figure out how to run multiple commands in one script and make it part of the `release` script in https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/.travis.yml#L39
* add another stage `releaseCpgClientLib` that just calls your script

Sounds like the last option is best - give it a try, it should automagically start building your branch when you push it (and you added it to the whitelist).

**Comment by fabsx00** [comment]
yep, I'm experimenting with just calling python-related testing and release in this PR here: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/185 - still failing on travis, but I think I'll get there some time today.

**Comment by fabsx00** [comment]
Building/testing already works: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/185

**Comment by fabsx00** [comment]
This is finally working. Excuse the commit history.
